// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordModel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hxl.server.model;

public class SensitiveWordModel implements Cloneable, java.io.Serializable
{
    public long companyId;

    public long
    getCompanyId()
    {
        return companyId;
    }

    public void
    setCompanyId(long _companyId)
    {
        companyId = _companyId;
    }

    public java.util.List<String> wordList;

    public java.util.List<String>
    getWordList()
    {
        return wordList;
    }

    public void
    setWordList(java.util.List<String> _wordList)
    {
        wordList = _wordList;
    }

    public SensitiveWordModel()
    {
    }

    public SensitiveWordModel(long companyId, java.util.List<String> wordList)
    {
        this.companyId = companyId;
        this.wordList = wordList;
    }

    public boolean
    equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SensitiveWordModel _r = null;
        if(rhs instanceof SensitiveWordModel)
        {
            _r = (SensitiveWordModel)rhs;
        }

        if(_r != null)
        {
            if(companyId != _r.companyId)
            {
                return false;
            }
            if(wordList != _r.wordList)
            {
                if(wordList == null || _r.wordList == null || !wordList.equals(_r.wordList))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::com::hxl::server::model::SensitiveWordModel");
        __h = IceInternal.HashUtil.hashAdd(__h, companyId);
        __h = IceInternal.HashUtil.hashAdd(__h, wordList);
        return __h;
    }

    public Object
    clone()
    {
        Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(companyId);
        SensitiveWordListHelper.write(__os, wordList);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        companyId = __is.readLong();
        wordList = SensitiveWordListHelper.read(__is);
    }

    public static final long serialVersionUID = -796654665L;
}
