// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hxl.server.MyMgr;

public final class _SensitiveWordServiceDelD extends Ice._ObjectDelD implements _SensitiveWordServiceDel
{
    public int GetSensitiveWord(final int roomId, final com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __observer)
        throws IceInternal.LocalExceptionWrapper
    {
        throw new Ice.CollocationOptimizationException();
    }

    public int TestToList(final int companyId, final TestListHolder list, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __observer)
        throws IceInternal.LocalExceptionWrapper
    {
        throw new Ice.CollocationOptimizationException();
    }
}
