// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hxl.server.MyMgr;

public abstract class _SensitiveWordServiceDisp extends Ice.ObjectImpl implements SensitiveWordService
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws CloneNotSupportedException
    {
        throw new CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::com::hxl::server::MyMgr::SensitiveWordService"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public final void GetSensitiveWord_async(AMD_SensitiveWordService_GetSensitiveWord __cb, int roomId)
    {
        GetSensitiveWord_async(__cb, roomId, null);
    }

    public final void TestToList_async(AMD_SensitiveWordService_TestToList __cb, int companyId)
    {
        TestToList_async(__cb, companyId, null);
    }

    public static Ice.DispatchStatus ___TestToList(SensitiveWordService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        int companyId;
        companyId = __is.readInt();
        __inS.endReadParams();
        AMD_SensitiveWordService_TestToList __cb = new _AMD_SensitiveWordService_TestToList(__inS);
        try
        {
            __obj.TestToList_async(__cb, companyId, __current);
        }
        catch(Exception ex)
        {
            __cb.ice_exception(ex);
        }
        return Ice.DispatchStatus.DispatchAsync;
    }

    public static Ice.DispatchStatus ___GetSensitiveWord(SensitiveWordService __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        int roomId;
        roomId = __is.readInt();
        __inS.endReadParams();
        AMD_SensitiveWordService_GetSensitiveWord __cb = new _AMD_SensitiveWordService_GetSensitiveWord(__inS);
        try
        {
            __obj.GetSensitiveWord_async(__cb, roomId, __current);
        }
        catch(Exception ex)
        {
            __cb.ice_exception(ex);
        }
        return Ice.DispatchStatus.DispatchAsync;
    }

    private final static String[] __all =
    {
        "GetSensitiveWord",
        "TestToList",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ___GetSensitiveWord(this, in, __current);
            }
            case 1:
            {
                return ___TestToList(this, in, __current);
            }
            case 2:
            {
                return ___ice_id(this, in, __current);
            }
            case 3:
            {
                return ___ice_ids(this, in, __current);
            }
            case 4:
            {
                return ___ice_isA(this, in, __current);
            }
            case 5:
            {
                return ___ice_ping(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 0L;
}
