// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.hxl.server.MyMgr;

public interface AMD_SensitiveWordService_GetSensitiveWord extends Ice.AMDCallback
{
    void ice_response(int __ret, com.hxl.server.model.SensitiveWordModel sensitiveWordList);
}
