server:
  port: 80

spring:
  # 激活多环境
  profiles:
    active: db
  datasource:
    # 数据库驱动类（MySQL 8.x用这个，5.x用 com.mysql.jdbc.Driver）
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库用户名
    username: ${DB_USERNAME:root}
    # 数据库密码
    password: ${DB_PASSWORD:123456}
    # 数据库连接URL（替换为你的数据库地址、端口和库名）
    url: jdbc:mysql://${DATABASE_IP:192.168.7.112}:${DATABASE_PORT:3306}/${DATABASE_NAME:fsboss}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false