// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.MyMgr;

final class _AMD_SensitiveWordService_GetSensitiveWord extends IceInternal.IncomingAsync implements AMD_SensitiveWordService_GetSensitiveWord
{
    public _AMD_SensitiveWordService_GetSensitiveWord(IceInternal.Incoming in)
    {
        super(in);
    }

    public void ice_response(int __ret, com.hxl.server.model.SensitiveWordModel sensitiveWordList)
    {
        if(__validateResponse(true))
        {
            try
            {
                IceInternal.BasicStream __os = this.__startWriteParams(Ice.FormatType.DefaultFormat);
                sensitiveWordList.__write(__os);
                __os.writeInt(__ret);
                this.__endWriteParams(true);
            }
            catch(Ice.LocalException __ex)
            {
                __exception(__ex);
                return;
            }
            __response();
        }
    }
}
