// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.MyMgr;

public abstract class Callback_SensitiveWordService_GetSensitiveWord extends Ice.TwowayCallback
{
    public abstract void response(int __ret, com.hxl.server.model.SensitiveWordModel sensitiveWordList);

    public final void __completed(Ice.AsyncResult __result)
    {
        SensitiveWordServicePrx __proxy = (SensitiveWordServicePrx)__result.getProxy();
        int __ret = 0;
        com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList = new com.hxl.server.model.SensitiveWordModelHolder();
        try
        {
            __ret = __proxy.end_GetSensitiveWord(sensitiveWordList, __result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret, sensitiveWordList.value);
    }
}
