// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.MyMgr;

public final class SensitiveWordServicePrxHelper extends Ice.ObjectPrxHelperBase implements SensitiveWordServicePrx
{
    private static final String __GetSensitiveWord_name = "GetSensitiveWord";

    public int GetSensitiveWord(int roomId, com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList)
    {
        return GetSensitiveWord(roomId, sensitiveWordList, null, false);
    }

    public int GetSensitiveWord(int roomId, com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, java.util.Map<String, String> __ctx)
    {
        return GetSensitiveWord(roomId, sensitiveWordList, __ctx, true);
    }

    private int GetSensitiveWord(int roomId, com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "GetSensitiveWord", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("GetSensitiveWord");
                    __delBase = __getDelegate(false);
                    _SensitiveWordServiceDel __del = (_SensitiveWordServiceDel)__delBase;
                    return __del.GetSensitiveWord(roomId, sensitiveWordList, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId)
    {
        return begin_GetSensitiveWord(roomId, null, false, null);
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx)
    {
        return begin_GetSensitiveWord(roomId, __ctx, true, null);
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, Ice.Callback __cb)
    {
        return begin_GetSensitiveWord(roomId, null, false, __cb);
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_GetSensitiveWord(roomId, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, Callback_SensitiveWordService_GetSensitiveWord __cb)
    {
        return begin_GetSensitiveWord(roomId, null, false, __cb);
    }

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx, Callback_SensitiveWordService_GetSensitiveWord __cb)
    {
        return begin_GetSensitiveWord(roomId, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__GetSensitiveWord_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __GetSensitiveWord_name, __cb);
        try
        {
            __result.__prepare(__GetSensitiveWord_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(roomId);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_GetSensitiveWord(com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __GetSensitiveWord_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            sensitiveWordList.value = new com.hxl.server.model.SensitiveWordModel();
            sensitiveWordList.value.__read(__is);
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public boolean GetSensitiveWord_async(AMI_SensitiveWordService_GetSensitiveWord __cb, int roomId)
    {
        Ice.AsyncResult __r;
        try
        {
            __checkTwowayOnly(__GetSensitiveWord_name);
            __r = begin_GetSensitiveWord(roomId, null, false, __cb);
        }
        catch(Ice.TwowayOnlyException ex)
        {
            __r = new IceInternal.OutgoingAsync(this, __GetSensitiveWord_name, __cb);
            __r.__exceptionAsync(ex);
        }
        return __r.sentSynchronously();
    }

    public boolean GetSensitiveWord_async(AMI_SensitiveWordService_GetSensitiveWord __cb, int roomId, java.util.Map<String, String> __ctx)
    {
        Ice.AsyncResult __r;
        try
        {
            __checkTwowayOnly(__GetSensitiveWord_name);
            __r = begin_GetSensitiveWord(roomId, __ctx, true, __cb);
        }
        catch(Ice.TwowayOnlyException ex)
        {
            __r = new IceInternal.OutgoingAsync(this, __GetSensitiveWord_name, __cb);
            __r.__exceptionAsync(ex);
        }
        return __r.sentSynchronously();
    }

    private static final String __TestToList_name = "TestToList";

    public int TestToList(int companyId, TestListHolder list)
    {
        return TestToList(companyId, list, null, false);
    }

    public int TestToList(int companyId, TestListHolder list, java.util.Map<String, String> __ctx)
    {
        return TestToList(companyId, list, __ctx, true);
    }

    private int TestToList(int companyId, TestListHolder list, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "TestToList", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("TestToList");
                    __delBase = __getDelegate(false);
                    _SensitiveWordServiceDel __del = (_SensitiveWordServiceDel)__delBase;
                    return __del.TestToList(companyId, list, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_TestToList(int companyId)
    {
        return begin_TestToList(companyId, null, false, null);
    }

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx)
    {
        return begin_TestToList(companyId, __ctx, true, null);
    }

    public Ice.AsyncResult begin_TestToList(int companyId, Ice.Callback __cb)
    {
        return begin_TestToList(companyId, null, false, __cb);
    }

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_TestToList(companyId, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_TestToList(int companyId, Callback_SensitiveWordService_TestToList __cb)
    {
        return begin_TestToList(companyId, null, false, __cb);
    }

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx, Callback_SensitiveWordService_TestToList __cb)
    {
        return begin_TestToList(companyId, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__TestToList_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __TestToList_name, __cb);
        try
        {
            __result.__prepare(__TestToList_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(companyId);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public int end_TestToList(TestListHolder list, Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __TestToList_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            list.value = TestListHelper.read(__is);
            int __ret;
            __ret = __is.readInt();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public boolean TestToList_async(AMI_SensitiveWordService_TestToList __cb, int companyId)
    {
        Ice.AsyncResult __r;
        try
        {
            __checkTwowayOnly(__TestToList_name);
            __r = begin_TestToList(companyId, null, false, __cb);
        }
        catch(Ice.TwowayOnlyException ex)
        {
            __r = new IceInternal.OutgoingAsync(this, __TestToList_name, __cb);
            __r.__exceptionAsync(ex);
        }
        return __r.sentSynchronously();
    }

    public boolean TestToList_async(AMI_SensitiveWordService_TestToList __cb, int companyId, java.util.Map<String, String> __ctx)
    {
        Ice.AsyncResult __r;
        try
        {
            __checkTwowayOnly(__TestToList_name);
            __r = begin_TestToList(companyId, __ctx, true, __cb);
        }
        catch(Ice.TwowayOnlyException ex)
        {
            __r = new IceInternal.OutgoingAsync(this, __TestToList_name, __cb);
            __r.__exceptionAsync(ex);
        }
        return __r.sentSynchronously();
    }

    public static SensitiveWordServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SensitiveWordServicePrx)
            {
                __d = (SensitiveWordServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SensitiveWordServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SensitiveWordServicePrx)
            {
                __d = (SensitiveWordServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SensitiveWordServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SensitiveWordServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SensitiveWordServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SensitiveWordServicePrx)
            {
                __d = (SensitiveWordServicePrx)__obj;
            }
            else
            {
                SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static SensitiveWordServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SensitiveWordServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            SensitiveWordServicePrxHelper __h = new SensitiveWordServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::com::hxl::server::MyMgr::SensitiveWordService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _SensitiveWordServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _SensitiveWordServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, SensitiveWordServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static SensitiveWordServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            SensitiveWordServicePrxHelper result = new SensitiveWordServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
