// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SensitiveWordService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.MyMgr;

public interface SensitiveWordServicePrx extends Ice.ObjectPrx
{
    public int TestToList(int companyId, TestListHolder list);

    public int TestToList(int companyId, TestListHolder list, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_TestToList(int companyId);

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_TestToList(int companyId, Ice.Callback __cb);

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_TestToList(int companyId, Callback_SensitiveWordService_TestToList __cb);

    public Ice.AsyncResult begin_TestToList(int companyId, java.util.Map<String, String> __ctx, Callback_SensitiveWordService_TestToList __cb);

    public int end_TestToList(TestListHolder list, Ice.AsyncResult __result);

    public boolean TestToList_async(AMI_SensitiveWordService_TestToList __cb, int companyId);

    public boolean TestToList_async(AMI_SensitiveWordService_TestToList __cb, int companyId, java.util.Map<String, String> __ctx);

    public int GetSensitiveWord(int roomId, com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList);

    public int GetSensitiveWord(int roomId, com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, Callback_SensitiveWordService_GetSensitiveWord __cb);

    public Ice.AsyncResult begin_GetSensitiveWord(int roomId, java.util.Map<String, String> __ctx, Callback_SensitiveWordService_GetSensitiveWord __cb);

    public int end_GetSensitiveWord(com.hxl.server.model.SensitiveWordModelHolder sensitiveWordList, Ice.AsyncResult __result);

    public boolean GetSensitiveWord_async(AMI_SensitiveWordService_GetSensitiveWord __cb, int roomId);

    public boolean GetSensitiveWord_async(AMI_SensitiveWordService_GetSensitiveWord __cb, int roomId, java.util.Map<String, String> __ctx);
}
